name: Build and Deploy
on: [push]

jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

  build-react:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Dependencies
        run: |
          cd frontend
          npm install

      - name: Build React App
        run: |
          cd frontend
          npm run build

      - name: Upload React Build
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: frontend/build

  deploy-to-impaas:
    needs: [python-formatting, build-react]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Download React Build
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: frontend/build

      - name: Deploy to ImPaaS
        uses: /impaas/impaas-deploy@v3
        with:
          app-name: runescape-tracker
          deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
          method: PLATFORM
